[package]
name = "git_automate"
version = "0.1.0"
edition = "2021"

[dependencies]
git2 = "0.16"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde_json = "1.0"
# github.gitAuthentication